01:
	go run 01-httpSimple.go
02:
	go run 02-httpNewServeMux.go
03:
	go run 03-httpCustomhandlers.go
04:
	go run 04-httpHandlerFunc.go
05:
	go run 05-httpPassingVariablesToHandlers.go
06:
	go run 06-httpDefaultServeMux.go