01:
	go run 01-simple_timeout.go "timeout"

02:
	go run 02-server_deadline.go
    # And run browser to write localhost:8080/timeout

03:
	 go run 03-server_timeout_context.go
    # And run browser to write localhost:8080/timeout

