01:
	go run 01-httpSimple.go
02:
	go run 02-httpNewServeMux.go
03:
	go run 03-httpCustomhandlers.go
04:
	go run 04-httpHandlerFunc.go
05:
	go run 05-httpPassingVariablesToHandlers.go
06:
	go run 06-httpDefaultServeMux.go
07:
	go run 07-httpMiddlewareFlow.go
08:
	go run 08-httpMiddleware.go
09:
	go run 09-httpBasicAuth.go
10:
	go run 10-httpLogger.go
11:
	go run 11-httpLogger.go