01:
	go run 01-ReadWriteFile.go

02:
	go run 02-ReadFile.go

03:
	go run 03-ioutilPKG.go

04:
	go run 04-ReadFileVariety.go

05:
	go run 05-embedPkg.go

06:
	go run 06-ReadWriteBinaryFile.go

07:
	go run 07-ReadFileCaseStudy.go

08:
	go run 08-WriteFileCaseStudy.go

09:
	go run 09-JSONFile.go