01:
	echo "review array"
	go run 01-arrays.go
02:
	echo "ex array with func"
	go run 02-printarray.go
03:
	echo "review switch"
	go run 03-slice.go
04:
	echo "learn about Variadic Functions"
	go run 04-variadic.go


